In [1]:
#1: Use numpy to solve the following
	#(a) Generate the numpy vector [1 2 3 4 5] in 3 (three) different ways!
import numpy as np

a = np.array([1,2,3,4,5])
print a
b = np.zeros(5, dtype = int)
for i in range(0,5):
	b[i] = i+1
print b
c = np.arange(1,6)
print c

#2. Create a file that has these lines:
	#1
	#2
	#a
	#3

#3. Read the file into your notebook and print the lines
with open('hw3.txt', 'r+') as f:
	contents = f.read()
	print contents
#4. Read the lines and convert each entry to float and then print
	f.seek(0)
	with open('hw3copy.txt','r+') as wf:
		for line in f:
			try:
				nline = float(line)
				wf.write(str(nline) + "\n")
			except ValueError:
				wf.write(line + "is not a valid number\n")
		wf.seek(0)
		wcontents = wf.read()
		print wcontents


[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
1
2
a
3

1.0
2.0
a
is not a valid number
3.0

